// <auto-generated />
using System;
using LogiSyncAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogiSyncAPI.Migrations
{
    [DbContext(typeof(LogiSyncContext))]
    partial class LogiSyncContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogiSyncAPI.Models.EmpresaLogistica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmpresasLogisticas");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaLogisticaId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoNormalizadoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOriginalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaLogisticaId");

                    b.HasIndex("EstadoNormalizadoId");

                    b.HasIndex("EstadoOriginalId");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.EstadoNormalizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosNormalizados");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.EstadoOriginal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaLogisticaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaLogisticaId");

                    b.ToTable("EstadosOriginales");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.Evidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnvioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnvioId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNormalizadoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOriginalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.HasIndex("EstadoNormalizadoId");

                    b.HasIndex("EstadoOriginalId");

                    b.ToTable("HistorialEstados");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.TraduccionEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoNormalizadoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOriginalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoNormalizadoId");

                    b.HasIndex("EstadoOriginalId");

                    b.ToTable("TraduccionesEstados");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.Envio", b =>
                {
                    b.HasOne("LogiSyncAPI.Models.EmpresaLogistica", "EmpresaLogistica")
                        .WithMany()
                        .HasForeignKey("EmpresaLogisticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiSyncAPI.Models.EstadoNormalizado", "EstadoNormalizado")
                        .WithMany()
                        .HasForeignKey("EstadoNormalizadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogiSyncAPI.Models.EstadoOriginal", "EstadoOriginal")
                        .WithMany()
                        .HasForeignKey("EstadoOriginalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmpresaLogistica");

                    b.Navigation("EstadoNormalizado");

                    b.Navigation("EstadoOriginal");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.EstadoOriginal", b =>
                {
                    b.HasOne("LogiSyncAPI.Models.EmpresaLogistica", "EmpresaLogistica")
                        .WithMany()
                        .HasForeignKey("EmpresaLogisticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmpresaLogistica");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.Evidencia", b =>
                {
                    b.HasOne("LogiSyncAPI.Models.Envio", "Envio")
                        .WithMany("Evidencias")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Envio");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.HistorialEstado", b =>
                {
                    b.HasOne("LogiSyncAPI.Models.Envio", "Envio")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiSyncAPI.Models.EstadoNormalizado", "EstadoNormalizado")
                        .WithMany()
                        .HasForeignKey("EstadoNormalizadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiSyncAPI.Models.EstadoOriginal", "EstadoOriginal")
                        .WithMany()
                        .HasForeignKey("EstadoOriginalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Envio");

                    b.Navigation("EstadoNormalizado");

                    b.Navigation("EstadoOriginal");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.TraduccionEstado", b =>
                {
                    b.HasOne("LogiSyncAPI.Models.EstadoNormalizado", "EstadoNormalizado")
                        .WithMany()
                        .HasForeignKey("EstadoNormalizadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiSyncAPI.Models.EstadoOriginal", "EstadoOriginal")
                        .WithMany()
                        .HasForeignKey("EstadoOriginalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoNormalizado");

                    b.Navigation("EstadoOriginal");
                });

            modelBuilder.Entity("LogiSyncAPI.Models.Envio", b =>
                {
                    b.Navigation("Evidencias");

                    b.Navigation("HistorialEstados");
                });
#pragma warning restore 612, 618
        }
    }
}
